test-host: test  # name of container to execute test in

context:  # contexts to build images
  main:
    - build://devtools/dummy_arcadia/hello_world/hello_world: bin/hello
    - arcadia://library/recipes/docker_compose/example_with_recipe_config/Dockerfile: Dockerfile

save:
  test:
    - /tmp/output